// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mapoperation.proto

package pl.edu.agh.dsrg.sr.protos;

public final class DistributedMapProtos {
    private DistributedMapProtos() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
    }
    public interface MapOperationOrBuilder
            extends com.google.protobuf.MessageOrBuilder {

        // required .MapOperation.Type type = 1;
        boolean hasType();
        pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type getType();

        // required string key = 2;
        boolean hasKey();
        String getKey();

        // required string value = 3;
        boolean hasValue();
        String getValue();
    }
    public static final class MapOperation extends
            com.google.protobuf.GeneratedMessage
            implements MapOperationOrBuilder {
        // Use MapOperation.newBuilder() to construct.
        private MapOperation(Builder builder) {
            super(builder);
        }
        private MapOperation(boolean noInit) {}

        private static final MapOperation defaultInstance;
        public static MapOperation getDefaultInstance() {
            return defaultInstance;
        }

        public MapOperation getDefaultInstanceForType() {
            return defaultInstance;
        }

        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.internal_static_MapOperation_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.internal_static_MapOperation_fieldAccessorTable;
        }

        public enum Type
                implements com.google.protobuf.ProtocolMessageEnum {
            PUT(0, 0),
            REMOVE(1, 1),
            ;

            public static final int PUT_VALUE = 0;
            public static final int REMOVE_VALUE = 1;


            public final int getNumber() { return value; }

            public static Type valueOf(int value) {
                switch (value) {
                    case 0: return PUT;
                    case 1: return REMOVE;
                    default: return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<Type>
            internalGetValueMap() {
                return internalValueMap;
            }
            private static com.google.protobuf.Internal.EnumLiteMap<Type>
                    internalValueMap =
                    new com.google.protobuf.Internal.EnumLiteMap<Type>() {
                        public Type findValueByNumber(int number) {
                            return Type.valueOf(number);
                        }
                    };

            public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
                return getDescriptor().getValues().get(index);
            }
            public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
                return getDescriptor();
            }
            public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
                return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.getDescriptor().getEnumTypes().get(0);
            }

            private static final Type[] VALUES = {
                    PUT, REMOVE,
            };

            public static Type valueOf(
                    com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != getDescriptor()) {
                    throw new java.lang.IllegalArgumentException(
                            "EnumValueDescriptor is not for this type.");
                }
                return VALUES[desc.getIndex()];
            }

            private final int index;
            private final int value;

            private Type(int index, int value) {
                this.index = index;
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:MapOperation.Type)
        }

        private int bitField0_;
        // required .MapOperation.Type type = 1;
        public static final int TYPE_FIELD_NUMBER = 1;
        private pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type type_;
        public boolean hasType() {
            return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type getType() {
            return type_;
        }

        // required string key = 2;
        public static final int KEY_FIELD_NUMBER = 2;
        private java.lang.Object key_;
        public boolean hasKey() {
            return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public String getKey() {
            java.lang.Object ref = key_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    key_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getKeyBytes() {
            java.lang.Object ref = key_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                key_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        // required string value = 3;
        public static final int VALUE_FIELD_NUMBER = 3;
        private java.lang.Object value_;
        public boolean hasValue() {
            return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        public String getValue() {
            java.lang.Object ref = value_;
            if (ref instanceof String) {
                return (String) ref;
            } else {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                String s = bs.toStringUtf8();
                if (com.google.protobuf.Internal.isValidUtf8(bs)) {
                    value_ = s;
                }
                return s;
            }
        }
        private com.google.protobuf.ByteString getValueBytes() {
            java.lang.Object ref = value_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8((String) ref);
                value_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private void initFields() {
            type_ = pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type.PUT;
            key_ = "";
            value_ = "";
        }
        private byte memoizedIsInitialized = -1;
        public final boolean isInitialized() {
            byte isInitialized = memoizedIsInitialized;
            if (isInitialized != -1) return isInitialized == 1;

            if (!hasType()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasKey()) {
                memoizedIsInitialized = 0;
                return false;
            }
            if (!hasValue()) {
                memoizedIsInitialized = 0;
                return false;
            }
            memoizedIsInitialized = 1;
            return true;
        }

        public void writeTo(com.google.protobuf.CodedOutputStream output)
                throws java.io.IOException {
            getSerializedSize();
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, type_.getNumber());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                output.writeBytes(2, getKeyBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                output.writeBytes(3, getValueBytes());
            }
            getUnknownFields().writeTo(output);
        }

        private int memoizedSerializedSize = -1;
        public int getSerializedSize() {
            int size = memoizedSerializedSize;
            if (size != -1) return size;

            size = 0;
            if (((bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeEnumSize(1, type_.getNumber());
            }
            if (((bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(2, getKeyBytes());
            }
            if (((bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.CodedOutputStream
                        .computeBytesSize(3, getValueBytes());
            }
            size += getUnknownFields().getSerializedSize();
            memoizedSerializedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;
        @java.lang.Override
        protected java.lang.Object writeReplace()
                throws java.io.ObjectStreamException {
            return super.writeReplace();
        }

        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(
                com.google.protobuf.ByteString data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(
                com.google.protobuf.ByteString data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data).buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(
                byte[] data,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return newBuilder().mergeFrom(data, extensionRegistry)
                    .buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(java.io.InputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseDelimitedFrom(java.io.InputStream input)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseDelimitedFrom(
                java.io.InputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Builder builder = newBuilder();
            if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
                return builder.buildParsed();
            } else {
                return null;
            }
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(
                com.google.protobuf.CodedInputStream input)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input).buildParsed();
        }
        public static pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation parseFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            return newBuilder().mergeFrom(input, extensionRegistry)
                    .buildParsed();
        }

        public static Builder newBuilder() { return Builder.create(); }
        public Builder newBuilderForType() { return newBuilder(); }
        public static Builder newBuilder(pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation prototype) {
            return newBuilder().mergeFrom(prototype);
        }
        public Builder toBuilder() { return newBuilder(this); }

        @java.lang.Override
        protected Builder newBuilderForType(
                com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            Builder builder = new Builder(parent);
            return builder;
        }
        public static final class Builder extends
                com.google.protobuf.GeneratedMessage.Builder<Builder>
                implements pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperationOrBuilder {
            public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
                return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.internal_static_MapOperation_descriptor;
            }

            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
                return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.internal_static_MapOperation_fieldAccessorTable;
            }

            // Construct using pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.newBuilder()
            private Builder() {
                maybeForceBuilderInitialization();
            }

            private Builder(BuilderParent parent) {
                super(parent);
                maybeForceBuilderInitialization();
            }
            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }
            private static Builder create() {
                return new Builder();
            }

            public Builder clear() {
                super.clear();
                type_ = pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type.PUT;
                bitField0_ = (bitField0_ & ~0x00000001);
                key_ = "";
                bitField0_ = (bitField0_ & ~0x00000002);
                value_ = "";
                bitField0_ = (bitField0_ & ~0x00000004);
                return this;
            }

            public Builder clone() {
                return create().mergeFrom(buildPartial());
            }

            public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
                return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.getDescriptor();
            }

            public pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation getDefaultInstanceForType() {
                return pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.getDefaultInstance();
            }

            public pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation build() {
                pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(result);
                }
                return result;
            }

            private pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation buildParsed()
                    throws com.google.protobuf.InvalidProtocolBufferException {
                pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation result = buildPartial();
                if (!result.isInitialized()) {
                    throw newUninitializedMessageException(
                            result).asInvalidProtocolBufferException();
                }
                return result;
            }

            public pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation buildPartial() {
                pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation result = new pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation(this);
                int from_bitField0_ = bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.type_ = type_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.key_ = key_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.value_ = value_;
                result.bitField0_ = to_bitField0_;
                onBuilt();
                return result;
            }

            public Builder mergeFrom(com.google.protobuf.Message other) {
                if (other instanceof pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation) {
                    return mergeFrom((pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation)other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation other) {
                if (other == pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.getDefaultInstance()) return this;
                if (other.hasType()) {
                    setType(other.getType());
                }
                if (other.hasKey()) {
                    setKey(other.getKey());
                }
                if (other.hasValue()) {
                    setValue(other.getValue());
                }
                this.mergeUnknownFields(other.getUnknownFields());
                return this;
            }

            public final boolean isInitialized() {
                if (!hasType()) {

                    return false;
                }
                if (!hasKey()) {

                    return false;
                }
                if (!hasValue()) {

                    return false;
                }
                return true;
            }

            public Builder mergeFrom(
                    com.google.protobuf.CodedInputStream input,
                    com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws java.io.IOException {
                com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                        com.google.protobuf.UnknownFieldSet.newBuilder(
                                this.getUnknownFields());
                while (true) {
                    int tag = input.readTag();
                    switch (tag) {
                        case 0:
                            this.setUnknownFields(unknownFields.build());
                            onChanged();
                            return this;
                        default: {
                            if (!parseUnknownField(input, unknownFields,
                                    extensionRegistry, tag)) {
                                this.setUnknownFields(unknownFields.build());
                                onChanged();
                                return this;
                            }
                            break;
                        }
                        case 8: {
                            int rawValue = input.readEnum();
                            pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type value = pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type.valueOf(rawValue);
                            if (value == null) {
                                unknownFields.mergeVarintField(1, rawValue);
                            } else {
                                bitField0_ |= 0x00000001;
                                type_ = value;
                            }
                            break;
                        }
                        case 18: {
                            bitField0_ |= 0x00000002;
                            key_ = input.readBytes();
                            break;
                        }
                        case 26: {
                            bitField0_ |= 0x00000004;
                            value_ = input.readBytes();
                            break;
                        }
                    }
                }
            }

            private int bitField0_;

            // required .MapOperation.Type type = 1;
            private pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type type_ = pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type.PUT;
            public boolean hasType() {
                return ((bitField0_ & 0x00000001) == 0x00000001);
            }
            public pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type getType() {
                return type_;
            }
            public Builder setType(pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000001;
                type_ = value;
                onChanged();
                return this;
            }
            public Builder clearType() {
                bitField0_ = (bitField0_ & ~0x00000001);
                type_ = pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Type.PUT;
                onChanged();
                return this;
            }

            // required string key = 2;
            private java.lang.Object key_ = "";
            public boolean hasKey() {
                return ((bitField0_ & 0x00000002) == 0x00000002);
            }
            public String getKey() {
                java.lang.Object ref = key_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    key_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setKey(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000002;
                key_ = value;
                onChanged();
                return this;
            }
            public Builder clearKey() {
                bitField0_ = (bitField0_ & ~0x00000002);
                key_ = getDefaultInstance().getKey();
                onChanged();
                return this;
            }
            void setKey(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000002;
                key_ = value;
                onChanged();
            }

            // required string value = 3;
            private java.lang.Object value_ = "";
            public boolean hasValue() {
                return ((bitField0_ & 0x00000004) == 0x00000004);
            }
            public String getValue() {
                java.lang.Object ref = value_;
                if (!(ref instanceof String)) {
                    String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
                    value_ = s;
                    return s;
                } else {
                    return (String) ref;
                }
            }
            public Builder setValue(String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                bitField0_ |= 0x00000004;
                value_ = value;
                onChanged();
                return this;
            }
            public Builder clearValue() {
                bitField0_ = (bitField0_ & ~0x00000004);
                value_ = getDefaultInstance().getValue();
                onChanged();
                return this;
            }
            void setValue(com.google.protobuf.ByteString value) {
                bitField0_ |= 0x00000004;
                value_ = value;
                onChanged();
            }

            // @@protoc_insertion_point(builder_scope:MapOperation)
        }

        static {
            defaultInstance = new MapOperation(true);
            defaultInstance.initFields();
        }

        // @@protoc_insertion_point(class_scope:MapOperation)
    }

    private static com.google.protobuf.Descriptors.Descriptor
            internal_static_MapOperation_descriptor;
    private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internal_static_MapOperation_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\022mapoperation.proto\"i\n\014MapOperation\022 \n\004" +
                        "type\030\001 \002(\0162\022.MapOperation.Type\022\013\n\003key\030\002 " +
                        "\002(\t\022\r\n\005value\030\003 \002(\t\"\033\n\004Type\022\007\n\003PUT\020\000\022\n\n\006R" +
                        "EMOVE\020\001B1\n\031pl.edu.agh.dsrg.sr.protosB\024Di" +
                        "stributedMapProtos"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        internal_static_MapOperation_descriptor =
                                getDescriptor().getMessageTypes().get(0);
                        internal_static_MapOperation_fieldAccessorTable = new
                                com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                                internal_static_MapOperation_descriptor,
                                new java.lang.String[] { "Type", "Key", "Value", },
                                pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.class,
                                pl.edu.agh.dsrg.sr.protos.DistributedMapProtos.MapOperation.Builder.class);
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
    }

    // @@protoc_insertion_point(outer_class_scope)
}
